### PR TITLE
Jelena

### PR DESCRIPTION
**Pull request by Jpetrovic28**

### CODE REVIEW

**Review by Demetuva — APPROVED** [review]
Good job

**Comment by elshatomer77** [comment]
--------------------------$$$$$$
 ------------------------$$.......$$$
 ---------------------$$$..........$$$
 -------------------$$$.............$$$
 -----$*-$*-------$$................$$$
 -----$.$..$------$$..................$$
 -----+$.$$$----$$...................$$
 ---+*......$$----$$..................$$
 --$............$$---$$................$$
 -$..О...........$$$$................$$
 $................$$$:...............$$
 $$................$$$$............$$
 --*$$$................$$..........$$
 ------$................$$...........$$
 -----$.....$$............$.........$$
 ------$..$....$$..........;$......$$
 ----$$$$$......$........;$......$$
 --------$................;$.....$$
 -------$$.....................$$
 -------$$$..................$$
 ----$$$$$$$$$$$$$$$$$

**Review by AsiaBizub — COMMENTED** [review]
All good.

**Review by elshatomer77 — APPROVED** [review]
--------------------------$$$$$$
 ------------------------$$.......$$$
 ---------------------$$$..........$$$
 -------------------$$$.............$$$
 -----$*-$*-------$$................$$$
 -----$.$..$------$$..................$$
 -----+$.$$$----$$...................$$
 ---+*......$$----$$..................$$
 --$............$$---$$................$$
 -$..О...........$$$$................$$
 $................$$$:...............$$
 $$................$$$$............$$
 --*$$$................$$..........$$
 ------$................$$...........$$
 -----$.....$$............$.........$$
 ------$..$....$$..........;$......$$
 ----$$$$$......$........;$......$$
 --------$................;$.....$$
 -------$$.....................$$
 -------$$$..................$$
 ----$$$$$$$$$$$$$$$$$

**Comment by Olita87** [comment]
great one

**Comment by AsiaBizub** [comment]
:)

**Comment by Olita87** [comment]
sweet

**Pull request merged**
